server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_calendar
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

    #setting to help with debugging
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #setting to edite templates without restarting the server
  thymeleaf:
    cache: false